# https://bioconductor.statistik.tu-dortmund.de/packages/3.7/bioc/vignettes/ropls/inst/doc/ropls-vignette.pdf
library(ropls)
library(tidyverse)
library(doParallel)
library(doRNG)
library(foreach)
library(ape)
library(phytools)

tree <- read.tree("../../data/SSURefNR99_1200_slv_138_2_subset.tre")
N_SIM <- 999

## ================================================================
## Output directories (absolute paths, so that PSOCK workers whose
## working directory differs from the master can still write)
## ================================================================
dir.create("data/bugbase", recursive = TRUE, showWarnings = FALSE)
dir.create("data/traitar", recursive = TRUE, showWarnings = FALSE)
dir.create("data/bacdive", recursive = TRUE, showWarnings = FALSE)
dir.create("data/logs",    recursive = TRUE, showWarnings = FALSE)

DIR_BUGBASE <- normalizePath("data/bugbase", mustWork = TRUE)
DIR_TRAITAR <- normalizePath("data/traitar", mustWork = TRUE)
DIR_BACDIVE <- normalizePath("data/bacdive", mustWork = TRUE)
DIR_LOGS    <- normalizePath("data/logs",    mustWork = TRUE)

## ================================================================
## Threshold model: simulate BM liability on the phylogenetic tree,
## then quantize by the observed class proportions.
## The resulting null traits (a) have exactly the same class counts
## as observed, and (b) are clustered on the tree (lambda = 1).
## Thus the null distribution answers: "Is the discriminative power
## of SNE stronger than a random trait with the same degree of
## phylogenetic clustering?"
## ================================================================
sim_threshold_traits <- function(tree_sub, y_obs, n_sim = 999) {
    labs   <- levels(droplevels(y_obs))
    counts <- as.integer(table(droplevels(y_obs)))      # same order as labs

    liab <- phytools::fastBM(tree_sub, nsim = n_sim)    # n_tip x n_sim
    if (is.null(dim(liab))) {                           # nsim = 1 returns a vector
        liab <- matrix(liab, ncol = 1, dimnames = list(names(liab), NULL))
    }
    liab <- liab[tree_sub$tip.label, , drop = FALSE]

    lapply(seq_len(ncol(liab)), function(j) {
        v <- liab[, j]
        # Randomly assign which class occupies which segment of the
        # liability axis, avoiding any imposed class ordering
        perm   <- sample(seq_along(labs))
        blocks <- rep(labs[perm], times = counts[perm])
        out <- character(length(v))
        names(out) <- names(v)
        out[order(v)] <- blocks
        factor(out, levels = labs)
    })
}

## ================================================================
## Observed Q2/R2Y + phylogenetic null-distribution p values
##
## Same statistics (Q2cum, R2Ycum) and same one-sided p-value formula
## as the ropls permutation test (permI), but the null distribution is
## generated by the phylogenetic threshold model instead of by random
## label shuffling. Hence pQ2_phylo / pR2Y_phylo are the phylogenetic
## counterparts of ropls' pQ2 / pR2Y.
##
## The observed score matrix is stored as `scores` so that the plotting
## script can draw the PLS-DA scatter without refitting the model.
##
## `parallel = FALSE` by default: the outer foreach loops below already
## parallelise over traits, and nesting two parallel layers would make
## the workers compete for the same cores.
## ================================================================
phylo_perm_plsda <- function(x_all, trait_vec, tree, n_sim = 999,
                             predI = 2, crossvalI = 5, min_n = 20,
                             parallel = FALSE) {

    ## --- 1. Three-way alignment: has trait annotation / has embedding / on the tree ---
    ids <- Reduce(intersect, list(names(trait_vec)[!is.na(trait_vec)],
                                  rownames(x_all), tree$tip.label))
    if (length(ids) < min_n || length(unique(trait_vec[ids])) < 2) return(NULL)

    tr <- ape::keep.tip(tree, ids)
    if (is.null(tr$edge.length)) stop("tree has no branch lengths")
    min_pos <- min(tr$edge.length[tr$edge.length > 0])
    tr$edge.length[tr$edge.length == 0] <- min_pos / 1000
    tr$root.edge <- NULL

    ids <- tr$tip.label                                  # always follow the tree order
    x   <- as.matrix(x_all[ids, , drop = FALSE])
    y   <- factor(trait_vec[ids])

    fit_model <- function(yy) {
        ropls::opls(x, yy, predI = predI, crossvalI = crossvalI, permI = 0,
                    fig.pdfC = "none", info.txtC = "none")
    }
    get_stats <- function(m) {
        c(q2  = as.numeric(m@summaryDF[, "Q2(cum)"]),
          r2y = as.numeric(m@summaryDF[, "R2Y(cum)"]))
    }
    fit_safe <- function(yy) {
        tryCatch(get_stats(fit_model(yy)),
                 error = function(e) c(q2 = NA_real_, r2y = NA_real_))
    }

    ## --- 2. Observed model: keep the object so the scores can be stored ---
    m_obs  <- fit_model(y)
    obs    <- get_stats(m_obs)
    scores <- as.data.frame(m_obs@scoreMN)               # columns p1, p2

    ## --- 3. Null distribution: collect BOTH q2 and r2y ---
    y_sim <- sim_threshold_traits(tr, y, n_sim = n_sim)

    if (parallel) {
        null_mat <- foreach(yy = y_sim, .combine = rbind,
                            .packages = "ropls") %dopar% fit_safe(yy)
        null_mat <- matrix(as.numeric(null_mat), ncol = 2)
    } else {
        null_mat <- t(vapply(y_sim, fit_safe, numeric(2)))
    }
    colnames(null_mat) <- c("q2", "r2y")
    rownames(null_mat) <- NULL

    ## --- 4. One-sided p values, identical formula for both statistics ---
    pval <- function(null_v, obs_v) {
        ok <- !is.na(null_v)
        (1 + sum(null_v[ok] >= obs_v)) / (1 + sum(ok))
    }
    zval <- function(null_v, obs_v) {
        s <- sd(null_v, na.rm = TRUE)
        if (is.na(s) || s == 0) return(NA_real_)
        (obs_v - mean(null_v, na.rm = TRUE)) / s
    }

    list(q2_obs        = unname(obs["q2"]),
         r2y_obs       = unname(obs["r2y"]),
         pQ2_phylo     = pval(null_mat[, "q2"],  obs["q2"]),
         pR2Y_phylo    = pval(null_mat[, "r2y"], obs["r2y"]),
         z_q2          = zval(null_mat[, "q2"],  obs["q2"]),
         z_r2y         = zval(null_mat[, "r2y"], obs["r2y"]),
         q2_null_mean  = mean(null_mat[, "q2"],  na.rm = TRUE),
         r2y_null_mean = mean(null_mat[, "r2y"], na.rm = TRUE),
         # overfitting gap: observed vs null. A smaller observed gap than
         # the null gap indicates the model generalises rather than memorises.
         gap_obs       = unname(obs["r2y"] - obs["q2"]),
         gap_null_mean = mean(null_mat[, "r2y"] - null_mat[, "q2"], na.rm = TRUE),
         scores        = scores,                          # for the PLS-DA scatter
         y_obs         = y,                               # class label per taxon
         n_taxa        = length(ids),
         class_n       = table(y),
         n_sim         = n_sim,
         n_sim_ok      = sum(!is.na(null_mat[, "q2"])),
         q2_null       = null_mat[, "q2"],
         r2y_null      = null_mat[, "r2y"])
}

## Flatten the result list into one row, for use in Fig. 2B
as_row <- function(res, trait, source) {
    if (is.null(res)) return(NULL)
    data.frame(source        = source,
               trait         = trait,
               q2            = res$q2_obs,
               r2y           = res$r2y_obs,
               pQ2_phylo     = res$pQ2_phylo,
               pR2Y_phylo    = res$pR2Y_phylo,
               z_q2          = res$z_q2,
               z_r2y         = res$z_r2y,
               q2_null_mean  = res$q2_null_mean,
               r2y_null_mean = res$r2y_null_mean,
               gap_obs       = res$gap_obs,
               gap_null_mean = res$gap_null_mean,
               n_taxa        = res$n_taxa,
               n_sim         = res$n_sim,
               n_sim_ok      = res$n_sim_ok,
               class_n       = paste(names(res$class_n), res$class_n,
                                     sep = ":", collapse = "; "),
               stringsAsFactors = FALSE)
}

## Run one trait, record any error to a log file instead of losing it
run_trait <- function(traits_df, trait, embedding, tree, outdir, source,
                      n_sim = N_SIM) {
    res <- tryCatch({
        trait_vec <- setNames(as.character(traits_df[, trait]), rownames(traits_df))
        phylo_perm_plsda(embedding, trait_vec, tree, n_sim = n_sim)
    }, error = function(e) {
        writeLines(paste0(source, " / ", trait, ": ", conditionMessage(e)),
                   file.path(DIR_LOGS, paste0("error_", source, "_", trait, ".log")))
        NULL
    })
    if (!is.null(res)) {
        saveRDS(res, file = file.path(outdir, paste0("phyloperm_", trait, ".rds")))
    }
    as_row(res, trait, source)
}

n_cores <- max(1, detectCores() - 2)
cl <- makeCluster(n_cores)
registerDoParallel(cl)
registerDoRNG(20240809)                 # reproducible fastBM / sample across workers
PKGS <- c("ropls", "ape", "phytools")


## ================================================================
## bugbase
## ================================================================
# traits <- read.csv("data/traits_bugbase.csv", row.names = 1)
# traits[traits == ""] <- NA
# sne_embedding <- read.csv("../../data/social_niche_embedding_100.txt",
#                           row.names = 1, sep = " ", header = FALSE)

# traits_name <- c("Oxygen_Preference", "Gram_Status")
# stopifnot(all(traits_name %in% colnames(traits)))

# res_bugbase <- foreach(i = traits_name, .packages = PKGS,
#                        .combine = rbind, .errorhandling = "remove") %dopar% {
#     run_trait(traits, i, sne_embedding, tree, DIR_BUGBASE, "bugbase")
# }


## ================================================================
## Traitar
## ================================================================
# traits <- read.csv("data/trait_predcit.csv", row.names = 1)
# traits[traits == 3] <- 1

# ### Aerobe Facultative Anaerobe
# traits$Oxygen_Preference <- rep(0, nrow(traits))
# traits[traits$Aerobe == 1, "Oxygen_Preference"] <- 1
# traits[traits$Facultative == 1, "Oxygen_Preference"] <- 2
# traits[traits$Anaerobe == 1, "Oxygen_Preference"] <- 3
# traits[rowSums(traits[, c("Aerobe", "Facultative", "Anaerobe")]) != 1, "Oxygen_Preference"] <- NA

# ### Gram negative Gram positive
# traits$`Gram_Status` <- rep(0, nrow(traits))
# traits[traits$`Gram.negative` == 1, "Gram_Status"] <- 1
# traits[traits$`Gram.positive` == 1, "Gram_Status"] <- 2
# traits[rowSums(traits[, c("Gram.negative", "Gram.positive")]) != 1, "Gram_Status"] <- NA

# ### Cell shape
# traits$`cell_shape` <- rep(0, nrow(traits))
# traits[traits$Coccus == 1, "cell_shape"] <- 1
# traits[traits$`Bacillus.or.coccobacillus` == 1, "cell_shape"] <- 2
# traits[rowSums(traits[, c("Coccus", "Bacillus.or.coccobacillus")]) != 1, "cell_shape"] <- NA

# co_embedding <- read.csv("../../data/social_niche_embedding_100.txt",
#                          row.names = 1, sep = " ", header = FALSE)

# traits_name <- setdiff(colnames(traits),
#                        c("Aerobe", "Facultative", "Anaerobe",
#                          "Gram.negative", "Gram.positive",
#                          "Coccus", "Bacillus.or.coccobacillus"))

# res_traitar <- foreach(i = traits_name, .packages = PKGS,
#                        .combine = rbind, .errorhandling = "remove") %dopar% {
#     run_trait(traits, i, co_embedding, tree, DIR_TRAITAR, "traitar")
# }


## ================================================================
## bacDive
## ================================================================
traits <- read.csv("data/bacDive.csv")
traits <- traits[!duplicated(traits$`X16s_ID`), ]
rownames(traits) <- traits$`X16s_ID`

co_embedding <- read.csv("../../data/social_niche_embedding_100.txt",
                         row.names = 1, sep = " ", header = FALSE)
accessions_num <- str_split(rownames(co_embedding), "\\.", simplify = TRUE)[, 1]
df <- data.frame(accessions = accessions_num, embed_id = rownames(co_embedding))
inter_id <- intersect(rownames(traits), df$accessions)
df <- df %>% filter(accessions %in% inter_id)
traits <- traits[df$accessions, ]
rownames(traits) <- df$embed_id

traits$`Oxygen.Preference` <- rep(NA, nrow(traits))
traits <- traits %>% mutate(Oxygen.Preference = case_when(aerobe == 1 ~ "Aerobic", TRUE ~ Oxygen.Preference))
traits <- traits %>% mutate(Oxygen.Preference = case_when(`facultative.anaerobe` == 1 ~ "Facultatively", TRUE ~ Oxygen.Preference))
traits <- traits %>% mutate(Oxygen.Preference = case_when(anaerobe == 1 ~ "Anaerobic", TRUE ~ Oxygen.Preference))

for (v in c("mixed", "", "filament-shaped", "oval-shaped",
            "ovoid-shaped", "sphere-shaped", "spiral-shaped")) traits[traits == v] <- NA
traits[traits == "NA"] <- NA
traits[traits == "-"]  <- "no"
traits[traits == "+"]  <- "yes"
traits[traits == ""]   <- NA
traits[traits == "+;NA"] <- NA

traits[traits == 0] <- "no"
traits[traits == 1] <- "yes"
traits[traits == "mixed"] <- NA
traits[traits == "negative;positive"] <- NA
traits[traits == "negative;variable"] <- NA
traits[traits == ""] <- NA
traits[traits == "filament-shaped"] <- NA
traits[traits == "coccus-shaped"] <- "coccus"
traits[traits == "rod-shaped"] <- "bacillus"
traits[traits == "no;yes"] <- NA
traits <- traits %>%
    mutate(cell_shape = if_else(cell_shape %in% c("coccus", "bacillus"), cell_shape, NA))

agg_bac <- read.csv("data/agg_bac.csv") %>%
    filter(level_2 %in% c("assimilation", "builds_acid_from"))
agg_bac <- agg_bac[!duplicated(agg_bac$terms), ] %>% filter(terms %in% colnames(traits))
keep_terms <- c("gram_stain", "Oxygen.Preference", "cell_shape", "spore_formation", "motility", agg_bac$terms)
traits <- traits[, keep_terms]
traits <- traits[, colSums(is.na(traits)) < nrow(traits)]

traits_name <- colnames(traits)

res_bacdive <- foreach(i = traits_name, .packages = PKGS,
                       .combine = rbind) %dopar% {
    run_trait(traits, i, co_embedding, tree, DIR_BACDIVE, "bacdive")
}

stopCluster(cl)
registerDoSEQ()

## Report any trait that failed, instead of letting it disappear silently
err_files <- list.files(DIR_LOGS, pattern = "^error_", full.names = TRUE)
if (length(err_files)) {
    message("Failed traits (see data/logs/):")
    for (f in err_files) message("  ", readLines(f, warn = FALSE)[1])
}


## ================================================================
## Summary + FDR, for coloring in Fig. 2B
## ================================================================
# fig2b <- bind_rows(res_bugbase, res_traitar, res_bacdive) %>%
#     group_by(source) %>%
#     mutate(pQ2_phylo_fdr  = p.adjust(pQ2_phylo,  method = "BH"),
#            pR2Y_phylo_fdr = p.adjust(pR2Y_phylo, method = "BH")) %>%
#     ungroup() %>%
#     # pQ2 is the primary criterion; pR2Y is reported as a secondary statistic
#     arrange(pQ2_phylo, desc(z_q2))

# write.csv(fig2b, "data/fig2b_phylo_perm.csv", row.names = FALSE)
# print(fig2b, n = Inf)

# ## Traits whose p value hits the resolution floor 1/(n_sim_ok + 1):
# ## for these, rank by z_q2 rather than by p.
# fig2b %>%
#     filter(pQ2_phylo <= 1 / (n_sim_ok + 1)) %>%
#     select(source, trait, q2, z_q2, n_sim_ok) %>%
#     print(n = Inf)